name: CICD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"

    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements.txt
          pip install pytest
          pytest

  build-publish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2

      - run: |
          pip install build
          python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
